# Ensure the following repository secrets are set in GitHub:
# - CLOUD_RUN_SERVICE_ACCOUNT_DEV
# - CLOUD_RUN_SERVICE_ACCOUNT_STAGE
# - CLOUD_RUN_SERVICE_ACCOUNT_PROD

# This workflow requires the following branches to work properly:
# - main or master
# - dev
# - stage

# Note: Make sure to include a Dockerfile in your repository for building the Docker image.
name: Deployment to Cloud Run

on:
  push:
    branches: [main, master, dev, stage]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGION: us-east1
  # TODO: project-name CHANGE this to your desired project-name in GCP
  REPO_NAME: nextjs-cloud-run-test-app

jobs:
  setup-env:
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.env }}

    steps:
      - name: Setup Environment Name
        id: env-name

        run: echo "env=${{ fromJSON('{"main":"prod","dev":"dev","master":"prod","stage":"stage"}')[github.ref_name] }}" >> $GITHUB_OUTPUT

  build-and-deploy:
    needs: setup-env
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    env:
      ENV: "${{ needs.setup-env.outputs.env-name }}"
      PROJECT_ID: "zesty-${{ needs.setup-env.outputs.env-name }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate with Google Cloud
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets[format('CLOUD_RUN_SERVICE_ACCOUNT_{0}', env.ENV)] }}"

      # Setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and tag the docker image
        run: |-
          docker build . --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

      - name: Push the image to the Google Container Registry (GCR)
        run: |-
          docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy $REPO_NAME \
          --region $REGION \
          --image gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
          --platform "managed" \
          --quiet \
          --labels KEY1=VALUE1,KEY2=V5
